In [1]:
import pandas as pd

# Semicondutores

In [3]:
df = pd.read_csv("datasets/ai_chip_market.csv")

In [5]:
df

,year,chip_name,vendor,launch_date,memory_gb,fp16_tflops,tdp_watts,estimated_shipments_units,estimated_asp_usd,estimated_revenue_usd_m,description
0,2020,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,6128,15000,91.9,Volta data center GPU
1,2021,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,2719,15000,40.8,Volta data center GPU
2,2022,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,3098,15000,46.5,Volta data center GPU
3,2023,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,2572,15000,38.6,Volta data center GPU
4,2024,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,3437,15000,51.6,Volta data center GPU
...,...,...,...,...,...,...,...,...,...,...,...
115,2024,Apple M4 (NPU),Apple,2024-05-07,16,38,23,174,15000,2.6,Consumer NPU 38 TOPS
116,2025,Apple M4 (NPU),Apple,2024-05-07,16,38,23,1082,15000,16.2,Consumer NPU 38 TOPS
117,2026,Apple M4 (NPU),Apple,2024-05-07,16,38,23,776,15000,11.6,Consumer NPU 38 TOPS
118,2025,Apple M5 (NPU),Apple,2025-10-30,16,60,28,47,15000,0.7,M5 NPU generation
119,2026,Apple M5 (NPU),Apple,2025-10-30,16,60,28,809,15000,12.1,M5 NPU generation

In [9]:
df[["vendor", "year"]]

     vendor  year
0    NVIDIA  2020
1    NVIDIA  2021
2    NVIDIA  2022
3    NVIDIA  2023
4    NVIDIA  2024
..      ...   ...
115   Apple  2024
116   Apple  2025
117   Apple  2026
118   Apple  2025
119   Apple  2026

[120 rows x 2 columns]

In [10]:
df.rename(columns={"chip_name": "chip"}) # retorna um dataframe, não muda no mesmo lugar

,year,chip,vendor,launch_date,memory_gb,fp16_tflops,tdp_watts,estimated_shipments_units,estimated_asp_usd,estimated_revenue_usd_m,description
0,2020,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,6128,15000,91.9,Volta data center GPU
1,2021,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,2719,15000,40.8,Volta data center GPU
2,2022,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,3098,15000,46.5,Volta data center GPU
3,2023,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,2572,15000,38.6,Volta data center GPU
4,2024,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,3437,15000,51.6,Volta data center GPU
...,...,...,...,...,...,...,...,...,...,...,...
115,2024,Apple M4 (NPU),Apple,2024-05-07,16,38,23,174,15000,2.6,Consumer NPU 38 TOPS
116,2025,Apple M4 (NPU),Apple,2024-05-07,16,38,23,1082,15000,16.2,Consumer NPU 38 TOPS
117,2026,Apple M4 (NPU),Apple,2024-05-07,16,38,23,776,15000,11.6,Consumer NPU 38 TOPS
118,2025,Apple M5 (NPU),Apple,2025-10-30,16,60,28,47,15000,0.7,M5 NPU generation
119,2026,Apple M5 (NPU),Apple,2025-10-30,16,60,28,809,15000,12.1,M5 NPU generation

In [19]:
coluna_data = pd.to_datetime(df["launch_date"], format="%Y-%m-%d")
df["launch_date"] = coluna_data

In [20]:
df

,year,chip_name,vendor,launch_date,memory_gb,fp16_tflops,tdp_watts,estimated_shipments_units,estimated_asp_usd,estimated_revenue_usd_m,description
0,2020,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,6128,15000,91.9,Volta data center GPU
1,2021,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,2719,15000,40.8,Volta data center GPU
2,2022,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,3098,15000,46.5,Volta data center GPU
3,2023,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,2572,15000,38.6,Volta data center GPU
4,2024,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,3437,15000,51.6,Volta data center GPU
...,...,...,...,...,...,...,...,...,...,...,...
115,2024,Apple M4 (NPU),Apple,2024-05-07,16,38,23,174,15000,2.6,Consumer NPU 38 TOPS
116,2025,Apple M4 (NPU),Apple,2024-05-07,16,38,23,1082,15000,16.2,Consumer NPU 38 TOPS
117,2026,Apple M4 (NPU),Apple,2024-05-07,16,38,23,776,15000,11.6,Consumer NPU 38 TOPS
118,2025,Apple M5 (NPU),Apple,2025-10-30,16,60,28,47,15000,0.7,M5 NPU generation
119,2026,Apple M5 (NPU),Apple,2025-10-30,16,60,28,809,15000,12.1,M5 NPU generation

In [22]:
df["month"] = df["launch_date"].dt.month

In [24]:
df.head()

,year,chip_name,vendor,launch_date,memory_gb,fp16_tflops,tdp_watts,estimated_shipments_units,estimated_asp_usd,estimated_revenue_usd_m,description,month
0,2020,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,6128,15000,91.9,Volta data center GPU,5
1,2021,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,2719,15000,40.8,Volta data center GPU,5
2,2022,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,3098,15000,46.5,Volta data center GPU,5
3,2023,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,2572,15000,38.6,Volta data center GPU,5
4,2024,NVIDIA V100,NVIDIA,2017-05-10,32,100,300,3437,15000,51.6,Volta data center GPU,5

In [29]:
df["vendor"].unique(), df["year"].min(), df["year"].max()

(<StringArray>
 [     'NVIDIA',         'AMD',      'Google',         'AWS',    'Cerebras',
         'Groq',   'SambaNova', 'Tenstorrent',      'Huawei',   'Cambricon',
        'Apple']
 Length: 11, dtype: str,
 np.int64(2020),
 np.int64(2026))

In [35]:
df["estimated_shipments_units"].mean()

np.float64(117564.79166666667)